//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCPOC.Models
{
    using System.Web;
    using System.ComponentModel;

    public partial class Employee
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Department { get; set; }
        public int ID { get; set; }

        [DisplayName("Upload Image")]
        public string Image { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
